CREATE SEQUENCE SEQ_MEMBER;


DROP TABLE TBL_MEMBER;
CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
   MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
   MEMBER_NAME VARCHAR2(1000) NOT NULL,
   MEMBER_AGE NUMBER DEFAULT 0,
   MEMBER_GENDER VARCHAR2(1000) DEFAULT '선택 안함',
   CREATED_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'gkswltn0712@gmail.com', '1234', '한지수', 2, '선택 안함', SYSDATE, SYSDATE);
 INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'gkswltn2222@gmail.com', '4321', '허세웅', 4, '선택 안함', SYSDATE, SYSDATE);
 INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'gkswltn4444@gmail.com', '0865', '글라도스', 6, '선택 안함', SYSDATE, SYSDATE
);


SELECT MEMBER_EMAIL, MEMBER_PASSWORD
FROM TBL_MEMBER;

s

SELECT MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_GENDER, FROM TBL_MEMBER WHERE ID = ?