CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST(
   ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
   POST_TITLE VARCHAR2(1000) NOT NULL,
   POST_CONTENT VARCHAR2(1000) NOT NULL,
   POST_READ_COUNT NUMBER DEFAULT 0,
   MEMBER_ID NUMBER NOT NULL,
   CREATED_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

SELECT * FROM TBL_POST;

DROP 

SELECT P.ID, P.POST_TITLE, P.POST_CONTENT, P.POST_READ_COUNT, P.CREATED_DATE, P.UPDATED_DATE, P.MEMBER_ID, MEMBER_NAME FROM TBL_MEMBER M JOIN TBL_POST P ON M.ID = P.MEMBER_ID AND P.ID = ?