CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(1000) NOT NULL,
   POST_ID NUMBER NOT NULL,
   MEMBER_ID NUMBER NOT NULL,
   CREATED_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
   REFERENCES TBL_POST(ID),
   CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

SELECT * FROM TBL_REPLY;






SELECT * FROM TBL_MEMBER M JOIN TBL_REPLY R ON M.ID=R.MEMBER_ID
